### PR TITLE
add a instruction/note file under the tutorial folder to list all these explanations for variables in HRLDAS_setup file

### LINKED ISSUE #214: Variable issue in HRLDAS_setup_********_d1
Dear Professor:
Hello, I'm now trying to replace the initial data obtained by ERA5-land via create_forcing.exe with the data obtained by WRF, that is, the data in the file HRLDAS_setup_********_d1, but I'm not very clear about what the variables in it represent exactly. Can you please answer me?
acee0c3c-0972-4b6f-ae75-4e84e0899330

### PR DESCRIPTION
**Pull request by tslin2**
This PR is to solve the issue raised by #214 to provide a physical explanation of the variables in HRLDAS_setup initial condition file.

### CODE REVIEW

**Comment by cenlinhe** [comment]
A few suggestions:
1. too many commits for this one file update. Could you please just put this update in one single commit and re-submit the PR?
2. The "HRLDS" in the file name is wrong. It should be "HRLD**A**S".
Thanks!

**Comment by tslin2** [comment]
> A few suggestions:
> 
> 1. too many commits for this one file update. Could you please just put this update in one single commit and re-submit the PR?
> 2. The "HRLDS" in the file name is wrong. It should be "HRLD**A**S".
>    Thanks!

changes made.
Thanks!

**Review by cenlinhe — APPROVED** [review]
The file looks good to me. I approve it.

**Review by CharlesZheZhang — APPROVED** [review]
Thank you Tzu-Shun, this explanation file is clear to me

**Pull request merged**
